name: Rendering workflow

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

on:
  workflow_dispatch:
  schedule:
    - cron: '40 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Install libcurl
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.2.2
    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: 3.2
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Restore packages
      uses: r-lib/actions/setup-renv@v2
    - name: Render
      run: Rscript rende.R
    - name: Commmit repository
      run: |
        export TIMESTAMP=$(date +%y-%m-%d-%H-%M)
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add docs && git commit -m "Rendered $TIMESTAMP"
        git push
